baseURL = 'https://pmtang.github.io/'
languageCode = 'en-us'
title = 'Pengming Tang'
theme = 'hugo-resume'

[params]
address = "Munich, Germany"
email = "pengmingtang@gmail.com"

firstName = "Pengming"
lastName = "Tang"
profileImage = "img/profile.jpg"
favicon = "/favicon.ico"

showQr = true
showSkills = true

showExperience = true
showEducation = true
showBlog = true

[[params.handles]]
link = "https://www.linkedin.com/in/pengming-tang/"
name = "LinkedIn"

[[params.handles]]
link = "xing.to/pengming_tang"
name = "Xing"